### ISSUE TITLE
Integrating Bezier curves

### ISSUE THREAD

**Issue by Xender** [regebro/svg.path#15]
In svg.path from PiP, there is a following commet:
```
# Apparently it's impossible to integrate a Cubic Bezier, so
# this is a geometric approximation instead.
```

Well, Bezier cubes are polynomials, and AFAIK polynomials are one of simplest functions to integrate (well, sin and cos may be simpler).

So unless I'm missing some crucial detail here, computing the length of a Bezier curve can be done analytically, with major speedup.

On a side note: it should be noted that Path.point() does not guarantee points being equally distant on curve when linearly changing argument is used. Wighting dispatching of Path.point to segment by segment weights helps, but Bezier curves internally don't behave that way.

**Comment by regebro** [comment]
You are welcome to try. I did find several discussions that claimed there was no "closed-form solution" for it and even if there were, numerical approximation was better/faster. But I would not know.

**Comment by Xender** [comment]
Now I don't know, I think I have mistaken calculating integral of a polynomial of the curve by variable t with calculating length of the curve.
Surely, calculating the length is a problem that involves some integration, but I don't think it's the same as rather trivial polynomial integration anymore.

**Comment by Xender** [comment]
This seems to be about 3D curves, but I believe the point is the same: no close-form solution, only approximations possible.
http://steve.hollasch.net/cgindex/curves/cbezarclen.html

So yeah, looks like I've underestimated the problem for being just integral of a polynomial function, but it's more complex in reality.

**Comment by jcoffland** [comment]
A polynomial function is one that can be written in the form:

    f(x) = a_n x^n + a_n−1 x^(n−1) + . . . + a_2 x^2 + a_1 x + a_0

Where ``a_0`` through ``a_n`` are constants.

The cubic Bezier curve function looks like this:

    f(x) = A(1 - x)^3 + 3B(1 - x)^2 x + 3C(1 - x) x^2 + Dx^3

Where ``A``, ``B``, ``C`` and ``D`` are the control points and, for the purpose of evaluating an instance of the Bezier curve, are constants.  Multiplying everything out and collecting terms yields the expanded polynomial form:

    f(x) = (-A + 3B -3C + D)x^3 + (3A - 6B + 3B)x^2 + (-3A + 3B)x + A

If we say:

    a = -A + 3B - 3C + D
    b = 3A - 6B + 3B
    c = -3A + 3B
    d = A

Then we have the expanded polynomal:

    f(x) = ax^3 + bx^2 + cx + d

Whos indefinite integral is:

    a/4 x^4 + b/3 x^3 + c/2 x^2 + dx + E

Where ``E`` is a new constant introduced by integration.

The indefinite integral of the quadratic Bezier curve is:

    (-A + 3B - 3C + D)/4 x^4 + (3A - 6B + 3B)/3 x^3 + (-3A + 3B)/2 x^2 + Ax + E

So it is possible to integrate a cubic Bezier but this gives you the area under the curve not the length of the curve.  See: http://math.stackexchange.com/questions/922098/arc-length-of-general-polynomial

**Comment by MitchStam** [comment]
@jcoffland, thank you for providing this brilliant solution.  It's working wonderfully for me.  I was at first perplexed - I could not figure out how to use Vector2 control points as scalar A, B, C, D constants until I realized that Vector2.magnitude gives me the scalar value that is required.

Thank you for sharing your knowledge.  Best to you.

**Comment by jcoffland** [comment]
@MitchStan Glad it helped you.

**Comment by William4184** [comment]
@jcoffland thanks for the great solution. For anyone else who gets confused about how A, B, C and D got turned into constants, they are the y-values for each of the four control points (the x values being standard for a quadratic bezier as 0, 1/3, 2/3 and 1).
