### ISSUE TITLE
The length function for QuadraticBezier gives a divide by 0 error.

### ISSUE THREAD

**Issue by FGChecco** [regebro/svg.path#18]
This quadratic Bezier curve is valid and causes a divide by 0 error when calculating its length.

`QuadraticBezier(start=(158.125+225.5j), control=(157.5+225.5j), end=(156.875+225.5j))`

**Comment by MTician** [comment]
The anti-derivative currently used in the code to compute a quadratic's arc length this is only valid for open paths with P0 - 2*P1 + P2 != 0.
I'm going to submit a fix later today.

**Comment by regebro** [comment]
Fixes merged.
