### ISSUE TITLE
Path._is_closable() method and Path.closed attribute getter behavior don't match documented behavior.

### ISSUE THREAD

**Issue by MTician** [regebro/svg.path#20]
The Path._is_closable() method checks whether ANY segment in the Path object starts on the point where the path ends.
The Path.closed attribute getter consequentially doesn't reflect its documentation either.

**Comment by regebro** [comment]
_is_closable is used by the closed setter, and it checks that the end path coincides with a segment start. That's a "sanity check" to check that you have added the closing straight line. It does not have to be the starting segment, it can be any segment as a Path can have "subpaths". 

You are correct that the doctext for the closed setter is incorrect, I will fix this.
