### ISSUE TITLE
bug in Path.Arc._parameterize

### ISSUE THREAD

**Issue by MTician** [regebro/svg.path#25]
Arc((725.307482225571-915.5548199281527j), (202.79421639137703+148.77294617167183j), 225.6910319606926, 1, 1, (-624.6375539637027+896.5483089399895j))

raises a ValueError
From http://www.w3.org/TR/SVG/implnote.html#ArcImplementationNotes
looks like p/n is the inner product of two unit vectors, and thus will always be between -1 and 1.

using 
(p/n + 1) % 2 - 1
in the two places you take an inverse cosine will fix this.

**Comment by MTician** [comment]
I spoke too soon, this breaks some of your unittests... I'm looking into it.

**Comment by regebro** [comment]
Looks like the problem is that the arithmetic through the errors created by binary inaccuracies ends up being slightly less than -1.0 when it should be exactly -1.0. I made a check for that.
