### ISSUE TITLE
Question: are paths created by d() always going to be absolute?

### ISSUE THREAD

**Issue by daisieh** [regebro/svg.path#28]
I've been using your module and it's awesome; thank you so much for making/updating it!

In my code, I am relying on the current state of the path returned by d() being specified in Absolute terms; do you think this will always be the case, or at least the default case? I'd prefer it if I could depend on that being true. Thanks again!

**Comment by regebro** [comment]
Thanks!

It's possible that I in the future will remember of a path segment was absolute or relative when parsing, and in that case d() would return the same thing you passed in. But if that is the case, d() should also get a parameter to specify if you want absolute or relative positioning, so you would be able to specify that it's absolute in that case. But I have no plans for that.
