### ISSUE TITLE
UnboundLocalError: local variable 'segment_pos' referenced before assignment

### ISSUE THREAD

**Issue by erickmir** [regebro/svg.path#29]
I am trying to convert SVG Path to Polygon or Linestring based on js plugin: https://github.com/davidmcclure/svg-to-wkt/blob/master/svg-to-wkt.js.
Using next code:

```
DENSITY = 1

def pathPoints (path):
	points = []
	length = path.length()

	if length > 0:
		count = int(round(length * DENSITY))
		for i in range(count + 1):
			pos = (length * i) / count
			point = path.point(pos)
		        points.append(point)

	return points
```

Where the Path d attribute contains:
```
M 0.5 1.765625 L 0.5 -7.046875 L 5.5 -7.046875 L 5.5 1.76562
5 L 5.046875 1.40625 L 5.046875 -6.6875 L 0.96875 -6.6875 Z
```

But I am getting the next error:

```
  File "testsvg.py", line 45, in pathPoints
    point = path.point(pos)
  File "build\bdist.win32\egg\svg\path\path.py", line 369, in point
UnboundLocalError: local variable 'segment_pos' referenced before assignment
```

Why does this happen?

I hope you can help me. Many thanks...

**Comment by regebro** [comment]
Because position should be a value between 0 and 1. So change it to `pos = * i / count` and you will be fine. (Unless

 it's Python 2, then you should do `from __future__ import division` to fix the broken division handling in Python 2.)
