### ISSUE TITLE
ZeroDivisionError in Path. Arc._parameterize

### ISSUE THREAD

**Issue by santhoshtr** [regebro/svg.path#30]
For some particular Arc parameters, there is a zero division error thrown from Path. Arc._parameterize

Example: Arc(0j+70j, 35+35j, 0, 1, 0, 0+70j). Note the start and end being same.

```
in _parameterize
c = sqrt(abs((rx_sq * ry_sq - t1 - t2) / (t1 + t2)))
ZeroDivisionError: float division by zero
```

**Comment by regebro** [comment]
Well an arc from one point to the same point wouldn't really draw anything. I'm not sure what is expected here. One possibility would be to just special case this and do nothing.

**Comment by santhoshtr** [comment]
> One possibility would be to just special case this and do nothing.

I think that is acceptable

**Comment by regebro** [comment]
Fixed
