### ISSUE TITLE
Convert SVG to list of lines and arcs

### ISSUE THREAD

**Issue by Harvie** [regebro/svg.path#34]
Hello, i am working on SVG to g-code convertor for bCNC and i need way to subdivide the SVG to list of paths made just from LINEs and ARCs. Because g-code does not support anything else except lines and arcs. Is there way to do this using your library? That would mean to approximate and replace both Bezier types using lines (or arcs).

**Comment by justingruenberg** [comment]
I don’t know of a clean way to do this, but with a a Bézier you can solve the equation with the parameters for many t and then you really just have a lot of points with lines between them.

**Comment by Harvie** [comment]
@justingruenberg Sounds interresting, but too hard to implement myself. Do you know about some readily available code i can use for this?

**Comment by regebro** [comment]
That's basically what the `segment_length()` function in path.py does. It doesn't return the segments, it just returns their combined length, but you should be able to use the same recursive bisection technique, I think.

**Comment by justingruenberg** [comment]
[This](https://github.com/domoszlai/bezier2biarc/blob/master/Algorithm.cs) might be of help, though it is written in C#.

**Comment by Harvie** [comment]
I've found this python code for SVG.path linearization:
https://pypi.org/project/SVGCompress/#files

works like this:

```python
from svg_compression import *
comp_instance = Compress("test/test_vector.svg")
comp_instance.find_paths()                        # Extract path coordinates
comp_instance.linearize_paths(curve_fidelity = 10)     # Convert paths into polygons
#comp_instance.write(outputfile = "hrv.svg")
#print(comp_instance.linear_coords[0])
for path in comp_instance.linear_coords:
        p = path[0]
        print("g0 x%s y%s"%(str(p[0]),str(p[1])))
        for p in path:
                print("g1 x%s y%s"%(str(p[0]),str(p[1])))
```
Also we can throw away most of the library and it's dependencies

But we should disable arc linearization, because we can do arcs natively.

Thank you!
