### ISSUE TITLE
Switch to pkgutil namespace package for svg

### ISSUE THREAD

**Issue by jaraco** [regebro/svg.path#41]
In jaraco/svg.charts#24, I'm considering switching the `svg` namespace from a pkg_resource-style namespace to a pkgutil namespace. Doing so would make installations of `svg.*` packages incompatible across the switch boundary.

I imagine such a switch would be minimally impactful in practice. I suspect the usage of these two packages has only minor overlap. Even so, I would plan for a backward-compatible release and only if these packages can agree to make the switch in a shared timeframe.

What do you think? Are you aware of any other packages that supply `svg.*` packages?

**Comment by regebro** [comment]
I don't know of any others, and should be able to switch to pkgutil reasonably quickly.

**Comment by jaraco** [comment]
Cool. I've released svg.charts 5.0, which switches the style. Let me know if you'd like a pull request here.

**Comment by regebro** [comment]
A pull request would definitely make this go faster, I've a few other things I need to look at first, so it would take at least a week otherwise.
