### ISSUE TITLE
Extract absolute coordinates of all points of a path

### ISSUE THREAD

**Issue by Didou09** [regebro/svg.path#76]
Hi,

First of all thanks fo the code 👍 

Then, I'd like to extract all paths from a svg (Inkscape) and convert them to as many numpy arrays of shape (2, n) containing the absolute (x, y) coordinates of each point in the paths.

Is there a methods for this ?
Since you can already parse the svg Path commands, you can probably quite easily reconstruct the absolute coordinates command after command right ?

If the starting point is not known then it would be easy to add an optional keyword argument to allow the user to set it.

Something like:

`pts = Path.extract_absolute(start=(0, 0))`

Where `pts `would be a (2, n) or (n, 2) numpy array, or a list of tuple.
Where start would only be required if the first command is not absolute (`M`).

Is that already possible ? Would it be possible to implement it ?

**Comment by regebro** [comment]
A line contains infinite points, so you can't get them all. 
But this is what the `.point() ` method does. It takes a floating point value from 0 to 1, 0 representing the start and 1 the end, and you can get any point you want to the way.

**Comment by Didou09** [comment]
Thanks for your answer, but, unless I am misunderstanding, all path do not contain infinite points, a polygon for example only has a few points (all segments are straight lines). 
A path typically has a few remarkable points (start and end of each segment) and only contains infinite points if some segments are Arcs, Beziers or other curves.

In that case it would be nice to automatically extract the (x, y) coordinates of a discretized version of the Path, including all remarkable points and a discrtized version of all curves (using a discretization resolution provided by the user for example).

Any to do this easily ?

Thanks again

**Comment by regebro** [comment]
Yes, you can use `.point()`.

```
for n in range(0, 100):
    x, y = path.point(n/100)
```

If you don't want to cut corners, do each path segment separately.

**Comment by Didou09** [comment]
ok thanks

Also, for some reason, when I do it the way you propose, and then plot the extracted path using matplotlib I get a reversed y coordinate, I don't understand why, any idea ?

**Inkscape**
![image](https://user-images.githubusercontent.com/5929562/123398691-1b0b2480-d5a4-11eb-9897-7301490377ff.png)

**Matplotlib**
![image](https://user-images.githubusercontent.com/5929562/123398782-3413d580-d5a4-11eb-9db0-07c7ecc81f46.png)

**Comment by regebro** [comment]
SVG's coordinate system has zero at the top left of the document, so it's Inkscape being confusing by putting it as bottom left. In the SVG file it's the top left, so you have to flip the Y axis when drawing in matplotlib.
