### ISSUE TITLE
test_image failure

### ISSUE THREAD

**Issue by karl-nilsson** [regebro/svg.path#84]
First off, thanks for the excellent library!

I maintain this package for void linux, and when updating it to 5.1, I discovered one unit test fails. Specifically: test_image

```bash
        with open(filename, "rb") as fp:
            test_image = Image.open(fp, mode="r")
            diff = ImageChops.difference(test_image, self.image)
>           self.assertFalse(
                diff.getbbox(), "The resulting image is different from test_image.png"
            )
E           AssertionError: (27, 16, 466, 756) is not false : The resulting image is different from test_image.png

src/svg/path/tests/test_image.py:145: AssertionError
=========================== short test summary info ============================
FAILED src/svg/path/tests/test_image.py::ImageTest::test_image - AssertionErr...
========================= 1 failed, 47 passed in 2.08s =========================
```

Doing a little digging, it appears that Pillow's font rendering differs between platforms.

Here's a closeup of the differences in rendering:
![font_differences](https://user-images.githubusercontent.com/1455966/161391706-afe723d8-5332-4d79-89f2-d61f354c4607.png)

Here's the raw image diff:
![test_image_diff](https://user-images.githubusercontent.com/1455966/161391726-0b73bee4-589a-4517-a310-63433cac74f6.png)

**Comment by regebro** [comment]
Ugh. I got errors on Windows and Mac, but even on different unices? I guess I have to ditch the text.

**Comment by regebro** [comment]
OK, using the nearly-unreadable default font seems to work on both Ubuntu, Mac and Windows, so hopefully that should work on Void as well.

I won't release this separately though, but it will be a part of 6.0.

**Comment by karl-nilsson** [comment]
My suspicion is version and config discrepancies in freetype are enough to cause these subtle differences is rendering. 

I've disabled that one test in void's package, but I'll re-enable it with the next release.

Thanks again!

**Comment by karl-nilsson** [comment]
Hey, I just wanted to let you know your changes fixed this test.
Thanks again!
