### ISSUE TITLE
Unsupported valid SVG paths

### ISSUE THREAD

**Issue by Lucas-C** [regebro/svg.path#89]
Hi!

I have discovered some valid SVG paths that your library does not seem to support:
* `M 0. .1` and `M0..1` should be parsable as `Move(to=.1j)`
* `M -7e-5 -4e-5` should be parsable as `Move(to=(7e-5 - 4e-5j))`

I mean "valid" in the sense that the SVG viewers I checked were able to read those paths (Firefox notably)

**Comment by Lucas-C** [comment]
My bad, that was just a typo.

`M -7e-5 -4e-5` should be parsable as `Move(to=(-7e-5 - 4e-5j))`

**Comment by regebro** [comment]
OK, done

**Comment by Lucas-C** [comment]
I see you fixed this in https://github.com/regebro/svg.path/commit/d43af9f, thank you!

Do you have an estimation on when there will be a new release of `svg.path`?

**Comment by Lucas-C** [comment]
Hi @regebro!

`svg.path` latest release, v6.1, does not include this fix.
Do you think you could release a v6.2, please?

**Comment by regebro** [comment]
OK, done.

**Comment by Lucas-C** [comment]
Thank you!

**Comment by gewyvoso** [comment]
hello author. i've seen your nice posts on StackExchange, [\[1\]](https://stackoverflow.com/questions/14399406/implementing-svg-arc-curves-in-python?answertab=createdasc), [\[2\]](https://stackoverflow.com/questions/13879230/library-for-svg-path-calculations?answertab=createdasc), & [\[3\]](https://codereview.stackexchange.com/questions/28502/svg-path-parsing?answertab=createdasc). this was in fact mentioned in [comment on Jul 17, 2013 at 14:08](https://codereview.stackexchange.com/questions/28502/svg-path-parsing?answertab=createdasc#comment44922_28565). please also see [the comment made Jul 17, 2013 at 18:11](https://codereview.stackexchange.com/questions/28502/svg-path-parsing?answertab=createdasc#comment44929_28565)
