### ISSUE TITLE
.d()

### ISSUE THREAD

**Issue by perrineco** [regebro/svg.path#98]
Hello,

When I try to use path.d() I get this error : path_str = new_path.d()
AttributeError: 'str' object has no attribute 'd'

What should I do ? Thanks a lot for your help,

**Comment by regebro** [comment]
You seem to try to call `.d()` on a string object. But it's not a method on strings, it's a method on `Path` objects.

If you paste your code, and try to explain what you are trying to accomplish, I might be able to help you.
